# Generated by Django 4.2.4 on 2024-01-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_forgot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgot',
            old_name='email',
            new_name='user',
        ),
    ]
